# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net



name: Build ASP.NET Core App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use your actual version (e.g. 7.0.x or 6.0.x)

    - name: Restore dependencies
      run: dotnet restore aspnetcoreapp/aspnetcoreapp.sln

    - name: Build project
      run: dotnet build aspnetcoreapp/aspnetcoreapp.sln --configuration Release --no-restore

    - name: Run tests (optional)
      run: dotnet test aspnetcoreapp/aspnetcoreapp.sln --no-build --verbosity normal
