# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net



name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: List files (debug)
      run: ls -R

    - name: Restore dependencies
      working-directory: aspnetcoreapp
      run: dotnet restore aspnetcoreapp.sln

    - name: Build solution
      working-directory: aspnetcoreapp
      run: dotnet build aspnetcoreapp.sln --no-restore --configuration Release

    - name: Test solution
      working-directory: aspnetcoreapp
      run: dotnet test aspnetcoreapp.sln --no-build --verbosity normal

